test:
  stage: test
  script:
    - npm install;
    - ./node_modules/.bin/mocha ./test -R 'json' > ./test-results.$(date --iso-8601=minute).json;
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - ./test-results*

pages:
  stage: deploy
  script:
  - mv www public
  artifacts:
    paths:
    - public
  only:
  - master
