
test:
  image: selenium/standalone-chrome
  timeout: 10m
  stage: test
  script:
    - pwd;
    #- sudo apt-get update >> apt.log;
    #- sudo apt-get install -y chromium >> apt.log;
    - npm install --silent;
    - export PATH=$PATH:./node_modules/.bin;
    - mocha --exit --recursive ./tests/tests/ --reporter mocha-multi-reporters --reporter-options configFile=./tests/reporter.config.json;
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - ./apt.log
      - ./test-results.*
    reports:
      junit: test-results.xml

pages:
  stage: deploy
  script:
  - mv www public
  artifacts:
    paths:
    - public
  only:
  - master
  - staging
