
test:
  image: gitpod/workspace-full
  timeout: 10m
  stage: test
  script:
    - pwd;
    - sudo apt-get update >> apt.log;
    - sudo apt-get install -y firefox >> apt.log;
    - npm install --silent;
    - export PATH=$PATH:./node_modules/.bin;
    - mocha ./tests -R 'json' > ./test-results.json;
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - ./apt.log
      - ./test-results.json

pages:
  stage: deploy
  script:
  - mv www public
  artifacts:
    paths:
    - public
  only:
  - master
