
tasks:
  - init: npm install -g eslint
vscode:
  extensions:
    - mhutchie.git-graph
    - ritwickdey.liveserver
    - zaaack.markdown-editor
    - dbaeumer.vscode-eslint
    - hbenl.vscode-mocha-test-adapter
    - eamodio.gitlens
